
name: main

on:
  workflow_call:
    inputs:
      app_env:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      lambda_name:
        required: true
        type: string
      ecr_repository_name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  SH8: $(echo ${GITHUB_SHA} | cut -c1-8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws_region }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Get short commit
      run: |
        echo "SH8=$(echo ${{ env.SH8 }})" >> $GITHUB_ENV

    - name: Create Lambda Package
      run: |
        mkdir lambda_package
        cp -r ./ ./lambda_package
        zip -r lambda_package.zip ./lambda_package
        rm -rf ./lambda_package

    - name: Upload Lambda Package
      run: |
        aws lambda update-function-code --function-name  ${{ inputs.lambda_name }} --zip-file fileb://lambda_package.zip