
name: main

on:
  workflow_call:
    inputs:
      app_env:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      lambda_name:
        required: true
        type: string
      ecr_repository_name:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_ACCOUNT_ID:
        required: true

env:
  SH8: $(echo ${GITHUB_SHA} | cut -c1-8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws_region }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    
    - name: Get short commit
      run: |
        echo "SH8=$(echo ${{ env.SH8 }})" >> $GITHUB_ENV

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: |
          ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{inputs.aws_region}}.amazonaws.com/${{ inputs.ecr_repository_name }}:${{ env.SH8 }}
          ${{secrets.AWS_ACCOUNT_ID}}.dkr.ecr.${{inputs.aws_region}}.amazonaws.com/${{ inputs.ecr_repository_name }}:latest

  sync:
    runs-on: ubuntu-latest
    env:
      STAGE: ${{ inputs.app_env }}
    environment:
      name: ${{ inputs.app_env }}
    needs: build
    steps:

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ inputs.aws_region }}

    - name: Get short commit
      run: |
        echo "SH8=$(echo ${{ env.SH8 }})" >> $GITHUB_ENV
    
    - name: Changed the lambda image
      run: |
        aws lambda update-function-code --function-name  ${{ inputs.lambda_name }} --image-uri $ECR_REGISTRY/${{ inputs.ecr_repository_name }}:${{ env.SH8 }}
