---
name: 📦🚀 [Staging] Lambda Authorizer
on:
  push:
    branches:
      - develop
  workflow_dispatch:
  
jobs:
  build-stg:
    uses: ./.github/workflows/main.yml
    with:
      app_env: stg
      aws_region: us-east-1
      lambda_name: lanchonete-lambda-authorizer-stg
      ecr_repository_name: lanchonete-lambda-authorizer-stg-repository
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
